version: "3.9"
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    image: esg-scoring:live
    command: uvicorn apps.api.main:app --host 0.0.0.0 --port 8000
    ports: ["8000:8000"]
    env_file: [.env]
    environment:
      - PYTHONUNBUFFERED=1
      - SEED=42
      - PYTHONHASHSEED=0
      - ALLOW_NETWORK=${ALLOW_NETWORK:-false}
      - LIVE_EMBEDDINGS=${LIVE_EMBEDDINGS:-false}
    volumes: [".:/app:rw"]
    networks: [esgnet]

  runner:
    image: esg-scoring:live
    env_file: [.env]
    working_dir: /app
    entrypoint: ["/bin/bash","-lc"]
    environment:
      - SEED=42
      - PYTHONHASHSEED=0
      - ALLOW_NETWORK=${ALLOW_NETWORK:-false}
      - LIVE_EMBEDDINGS=${LIVE_EMBEDDINGS:-false}
    volumes: [".:/app:rw"]
    networks: [esgnet]
networks: { esgnet: {} }
