name: ci-cp-gates
on: [push, pull_request]
jobs:
  cp:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: "3.11" }
      - run: python -m venv .venv && . .venv/bin/activate && pip install -r requirements.txt || true
      - run: . .venv/bin/activate && pytest -q -k "cp"
